apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: microservices
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/roko1987-k8s/dod-santiago.git
    targetRevision: main
    path: app
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
